### PR TITLE
Switch to OAuth

### PR DESCRIPTION
**Pull request by ghost**
This is all it takes to use OAuth instead of user/pass login, along with a few minutes of setup on the part of whoever owns the reddit account the bot will use, so I see no reason to postpone. The site_name parameter will point PRAW to a block of a config file that lives on the machine running the script, which will contain the app ID, secret, and OAuth refresh token. With this information, all we need to do is call reddit.refresh_access_information(). This way we'll be future-proofed, and we can take advantage of reddit's allowance of one API call every second (instead of every two seconds for logged-in accounts) for OAuth users.

### CODE REVIEW

**Comment by ghost** [comment]
The second commit switches mechanize out for requests. The Python version of mechanize isn't well-supported and is incompatible with Python 3.

**Comment by ghost** [comment]
The third commit uses the PRAW submission object's is_self attribute. Also, my IDE replaced all your tabs with spaces. ¯\_(ツ)_/¯

**Comment by RedditBotting** [comment]
Thank god for whatever editor you're using, I didn't even realize my Sublime was set to not use spaces for tab -_____-

I'm going to go ahead and merge this; it looks like there's an issue with URLArchiver and the requests, though part of it could be that it seems my while loop is goofy.

**Comment by ghost** [comment]
I'm glad the tabs were unintentional. :P

**Comment by ghost** [comment]
Also, it did occur to me after I'd already committed the PR that after the `if req.status_code == 200` block, there should really be an `else` block that _also_ increments the counter. Requests doesn't throw exceptions for HTTP errors, it simply puts the error code in the request object's status_code attribute (as you see, obviously). The exception (the exception exception, if you will), for some reason, is timeouts, for which it throws `requests.exceptions.Timeout`.

**Pull request merged**
